const URL='https://uwgqlnvneqzcgzeroabm.supabase.co',KEY='sb_publishable__Yt-7wbq8c2EXgZkwdeQUg_16vy_cNf';const typeNames={resume:'Resyume',motivation_letter:'Motivatsion xat',certificate:'Sertifikat',grant_result:'Grant natijasi'};let client,user,docs=[];const status=m=>{const e=document.getElementById('docsStatus');if(e)e.textContent=m;};const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function render(){const list=document.getElementById('docsList');if(!docs.length){list.innerHTML='<div class="store-empty">Hozircha hujjat yo‘q.</div>';return;}list.innerHTML=docs.map(d=>`<article class="doc-card"><div class="doc-card-icon"><i class="fa-solid fa-file-lines"></i></div><div class="doc-card-body"><span class="support-kicker">${esc(typeNames[d.document_type])}</span><h3>${esc(d.title)}</h3><p>${d.file_path?'Fayl biriktirilgan. ':''}${d.content?'Matnli qoralama mavjud.':'Faqat sarlavha saqlangan.'}</p><small>${new Date(d.updated_at).toLocaleDateString('uz-UZ')}</small><div class="doc-card-actions">${d.file_path?`<button type="button" class="btn btn-secondary btn-sm" data-doc-file="${d.id}">Faylni ochish</button>`:''}${d.content?`<button type="button" class="btn btn-secondary btn-sm" data-doc-view="${d.id}">Matnni ko‘rish</button>`:''}</div></div></article>`).join('');list.querySelectorAll('[data-doc-file]').forEach(b=>b.addEventListener('click',()=>openFile(b.dataset.docFile)));list.querySelectorAll('[data-doc-view]').forEach(b=>b.addEventListener('click',()=>openText(b.dataset.docView)));}
async function openFile(id){const doc=docs.find(d=>d.id===id);if(!doc?.file_path)return;const result=await client.storage.from('tayanch-documents').createSignedUrl(doc.file_path,300);if(result.error){status('Faylni ochib bo‘lmadi.');return;}window.open(result.data.signedUrl,'_blank','noopener,noreferrer');}
function openText(id){const doc=docs.find(d=>d.id===id);if(!doc)return;document.getElementById('docViewerTitle').textContent=doc.title;document.getElementById('docViewerContent').textContent=doc.content||'';document.getElementById('docViewer').hidden=false;}
async function load(){const r=await client.from('user_documents').select('id,document_type,title,content,file_path,updated_at').order('updated_at',{ascending:false});if(r.error)throw r.error;docs=r.data||[];render();}
function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(new Error("timeout")),ms));}
async function init(){try{const mod=await Promise.race([import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'),timeout(8000)]);client=mod.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});let s=await Promise.race([client.auth.getSession(),timeout(8000)]);if(!s.data?.session){const a=await Promise.race([client.auth.signInAnonymously(),timeout(8000)]);if(a.error)throw a.error;s=a;}user=s.data.session.user;status('Supabase akkauntingiz bilan bog‘langan.');await Promise.race([load(),timeout(8000)]);}catch(e){console.warn('[documents]',e);status('Akkaunt sessiyasi topilmadi.');document.getElementById('docsList').innerHTML='<div class="store-empty">Hujjatlarni yuklashning imkoni bo‘lmadi.</div>';}}
document.getElementById('docSaveBtn').addEventListener('click',async()=>{const btn=document.getElementById('docSaveBtn'),title=document.getElementById('docTitle').value.trim(),content=document.getElementById('docContent').value.trim(),type=document.getElementById('docType').value,file=document.getElementById('docFile').files[0];if(!title){status('Sarlavhani kiriting.');return;}btn.disabled=true;try{let filePath=null;if(file){filePath=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await client.storage.from('tayanch-documents').upload(filePath,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;}const ins=await client.from('user_documents').insert({user_id:user.id,document_type:type,title,content:content||null,file_path:filePath}).select('id,document_type,title,content,file_path,updated_at').single();if(ins.error)throw ins.error;docs=[ins.data,...docs];render();document.getElementById('docTitle').value='';document.getElementById('docContent').value='';document.getElementById('docFile').value='';status('Hujjat saqlandi.');}catch(e){console.warn('[documents save]',e);status('Saqlashda xatolik yuz berdi.');}finally{btn.disabled=false;}});init();

document.getElementById('docViewerClose')?.addEventListener('click',()=>{document.getElementById('docViewer').hidden=true;}); document.getElementById('docViewer')?.addEventListener('click',e=>{if(e.target.id==='docViewer')e.currentTarget.hidden=true;});
