(() => {
  const copy = {
    uz: { back:'Bosh sahifaga qaytish',tag:'Ixtiyoriy yordam',title:'Tayanch’ni <span class="gradient-text">qo‘llab-quvvatlang</span>',desc:'Sizning ko‘magingiz yangi kurslar, amaliy video-darslar va bepul ta’lim imkoniyatlarini rivojlantirishga yordam beradi.',whyTitle:'Yordamingiz nimaga xizmat qiladi?',benefit1:'Yangi AI, IELTS va Admission darslarini tayyorlashga',benefit2:'O‘quv materiallarini bepul saqlash va yaxshilashga',benefit3:'Yoshlar uchun amaliy imkoniyatlarni kengaytirishga',note:'Qo‘llab-quvvatlash to‘liq ixtiyoriy. Hech qanday kurs yoki xizmat bunga bog‘lanmaydi.',amountKicker:'1-qadam',amountTitle:'Miqdorni tanlang',customAmount:'Ixtiyoriy miqdor',methodKicker:'2-qadam',methodTitle:'To‘lov usuli',comingSoon:'Tez kunda',paymentNote:'Payme yoki Click merchant hisobi ulanmaguncha to‘lovni qabul qilish tugmasi faol emas.',submit:'Qo‘llab-quvvatlash'},
    en: { back:'Back to homepage',tag:'Optional support',title:'Support <span class="gradient-text">Tayanch</span>',desc:'Your support helps us create new courses, practical video lessons, and free learning opportunities.',whyTitle:'What will your support help with?',benefit1:'Creating new AI, IELTS, and Admission lessons',benefit2:'Keeping and improving learning materials for free',benefit3:'Expanding practical opportunities for young learners',note:'Support is completely optional. No course or service depends on it.',amountKicker:'Step 1',amountTitle:'Choose an amount',customAmount:'Custom amount',methodKicker:'Step 2',methodTitle:'Payment method',comingSoon:'Coming soon',paymentNote:'The payment button will activate after a Payme or Click merchant account is connected.',submit:'Support Tayanch'}
  };
  let lang = localStorage.getItem('tayanch_support_language') || 'uz';
  const setLanguage = next => { if (!copy[next]) return; lang=next; localStorage.setItem('tayanch_support_language',lang); document.querySelectorAll('[data-support-i18n]').forEach(el => { const value=copy[lang][el.dataset.supportI18n]; if (value) el.innerHTML=value; }); document.getElementById('supportUzBtn')?.classList.toggle('active',lang==='uz'); document.getElementById('supportEnBtn')?.classList.toggle('active',lang==='en'); };
  document.getElementById('supportUzBtn')?.addEventListener('click',()=>setLanguage('uz')); document.getElementById('supportEnBtn')?.addEventListener('click',()=>setLanguage('en'));
  const custom = document.getElementById('supportCustomAmount');
  document.querySelectorAll('.support-amount-option').forEach(btn => btn.addEventListener('click',()=>{ document.querySelectorAll('.support-amount-option').forEach(item=>item.classList.remove('selected')); btn.classList.add('selected'); if(custom) custom.value=''; }));
  custom?.addEventListener('input',()=>document.querySelectorAll('.support-amount-option').forEach(item=>item.classList.remove('selected')));
  document.getElementById('supportSubmitBtn')?.addEventListener('click',()=>window.alert(lang==='uz'?'To‘lov tizimlari tez kunda ulanadi.':'Payment methods will be connected soon.'));
  setLanguage(lang);
})();
