const copy={uz:{back:'Bosh sahifaga qaytish',tag:'Mukofotlar',title:'XP <span class="gradient-text">Do‘koni</span>',desc:'Yig‘ilgan XP’ni o‘zingizga kerakli raqamli imkoniyatlarga ixtiyoriy ravishda almashtiring.',loading:'Mukofotlar yuklanmoqda…',empty:'Hozircha faol mukofot yo‘q.',connected:'Supabase akkauntingiz bilan bog‘langan.',notConnected:'Akkaunt sessiyasi topilmadi.',buy:'Ochish',owned:'Olingan',need:'Yana {n} XP kerak',error:'Xaridni amalga oshirib bo‘lmadi. Keyinroq urinib ko‘ring.',success:'Mukofot muvaffaqiyatli ochildi.'},en:{back:'Back to homepage',tag:'Rewards',title:'XP <span class="gradient-text">Store</span>',desc:'Optionally exchange your earned XP for useful digital benefits.',loading:'Loading rewards…',empty:'No active rewards yet.',connected:'Connected to your Supabase account.',notConnected:'No account session found.',buy:'Unlock',owned:'Claimed',need:'Need {n} more XP',error:'The purchase could not be completed. Please try again later.',success:'Reward unlocked successfully.'}};
const URL='https://uwgqlnvneqzcgzeroabm.supabase.co',KEY='sb_publishable__Yt-7wbq8c2EXgZkwdeQUg_16vy_cNf'; let lang=localStorage.getItem('tayanch_store_language')||'uz'; let client=null,profile=null,purchases=new Set();
const text=k=>(copy[lang]||copy.uz)[k]||k; const setStatus=m=>{const e=document.getElementById('storeStatus');if(e)e.textContent=m;};
function renderText(){document.querySelectorAll('[data-store-i18n]').forEach(e=>{const v=text(e.dataset.storeI18n);if(v)e.innerHTML=v;});document.getElementById('storeUzBtn')?.classList.toggle('active',lang==='uz');document.getElementById('storeEnBtn')?.classList.toggle('active',lang==='en');renderItems();}
function renderItems(){const grid=document.getElementById('storeGrid');if(!grid)return;const items=grid._items||[];if(!items.length){grid.innerHTML=`<div class="store-empty">${text('empty')}</div>`;return;}const balance=Number(profile?.xp_total||0);document.getElementById('storeBalance').textContent=`${balance} XP`;grid.innerHTML=items.map(item=>{const owned=purchases.has(item.id), enough=balance>=item.xp_price;const label=owned?text('owned'):enough?text('buy'):text('need').replace('{n}',String(item.xp_price-balance));return `<article class="store-item ${owned?'owned':''}"><div class="store-item-icon">${item.icon}</div><div class="store-item-body"><h2>${item.title}</h2><p>${item.description}</p><div class="store-item-footer"><span class="store-price"><i class="fa-solid fa-bolt"></i>${item.xp_price} XP</span><button class="btn btn-primary btn-sm store-buy-btn" data-item-id="${item.id}" ${owned||!enough?'disabled':''}>${label}</button></div></div></article>`;}).join('');grid.querySelectorAll('[data-item-id]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.itemId,b)));}
function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(new Error("timeout")),ms));}
async function init(){try{const mod=await Promise.race([import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'),timeout(8000)]);client=mod.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});let {data}=await Promise.race([client.auth.getSession(),timeout(8000)]);if(!data?.session){const r=await Promise.race([client.auth.signInAnonymously(),timeout(8000)]);if(r.error)throw r.error;data=r.data;}if(!data?.session)throw new Error('session_missing');setStatus(text('connected'));const p=await Promise.race([client.from('profiles').select('xp_total').maybeSingle(),timeout(8000)]);if(p.error)throw p.error;profile=p.data||{xp_total:250};const list=await Promise.race([client.from('xp_store_items').select('id,title,description,xp_price,icon,entitlement').eq('is_active',true).order('xp_price'),timeout(8000)]);if(list.error)throw list.error;const grid=document.getElementById('storeGrid');grid._items=list.data||[];const owned=await client.from('xp_store_purchases').select('item_id').eq('status','granted');if(!owned.error)(owned.data||[]).forEach(x=>purchases.add(x.item_id));renderItems();}catch(e){console.warn('[xp-store]',e);setStatus(text('notConnected'));const _sg=document.getElementById('storeGrid');if(_sg)_sg.innerHTML=`<div class="store-empty">${text('error')}</div>`;}}
async function buy(id,button){if(!client||button.disabled)return;button.disabled=true;try{const {data,error}=await client.rpc('purchase_xp_item',{p_item_id:id});if(error)throw error;profile=data?.profile||profile;purchases.add(id);setStatus(text('success'));renderItems();}catch(e){console.warn('[xp-store purchase]',e);setStatus(text('error'));button.disabled=false;}}
document.getElementById('storeUzBtn')?.addEventListener('click',()=>{lang='uz';localStorage.setItem('tayanch_store_language',lang);renderText();});document.getElementById('storeEnBtn')?.addEventListener('click',()=>{lang='en';localStorage.setItem('tayanch_store_language',lang);renderText();});renderText();init();
